### ISSUE TITLE
update --version when releasing 

### ISSUE THREAD

**Issue by poquirion** [CanDIG/candig-ingest#8]
In candig-ingest/candig/ingest/ingest.py 

replace args = docopt(__doc__, version='ingest from-git-master') with some number

**Comment by jimmyhli** [comment]
OK, I will try to have it set up so it reads version from a single source, be it setup.py or some _version.py under the package

**Comment by jimmyhli** [comment]
https://github.com/CanDIG/candig-ingest/pull/10
